### ISSUE TITLE
Updated CAD Files

### ISSUE THREAD

**Issue by Markus-1984** [FrankenVoron/Tridex#1]
Hi FrankenVoron,

realy nice mod for the Trident. I like Tridex ;-)
Can you please update the CAD Files. I´ve looked into the f3d assembly and only see a few modifications. I would like to see the full assembly before I decide to build it.

Best regards
Markus

**Comment by eddietheengineer** [comment]
Check the additional CAD files I updated a few days ago--not in the main assembly, but should show you how the various components have changed!
