### ISSUE TITLE
Frame Calculator - I wonder how this works

### ISSUE THREAD

**Issue by seacred** [FrankenVoron/Tridex#19]
I wonder how this works - If a Trident Kit with 250x250x250 is needed to build this one why is there 350mm in x and 250mm in y?
Could you explain the calculator in some easy words?
What do i need to change if i want to build one based on a 300x300 Kit?
Will the length of the linear rails also be affected? I guess they should.
Thanks in Advance.

_Originally posted by @seacred in https://github.com/FrankenVoron/Tridex/issues/14#issuecomment-1567299056_

**Comment by evanvruggink** [comment]
Because the idle extruder takes space. So to gain this space back, you use 100mm extra width.
