### ISSUE TITLE
wrong orientation of [a]_b_drive_middle stl is upside down

### ISSUE THREAD

**Issue by ThomasDennisSp** [FrankenVoron/Tridex#5]
the [a]_b_drive_middle stl is not in the right orientation for easy printing and is upside down so that you have to bridge ca. 2cm but the [a]_a_drive_middle stl is the otherway os you dont have to bridge noticed it because it came lose in printing

**Comment by eddietheengineer** [comment]
fixed with latest file release! Thanks
